import { useEffect, useState } from 'react'
import { Gamepad2, Pencil, Plus, Search, Users } from 'lucide-react'
import ItemForm from './components/ItemForm'
import ImageGallery from './components/ImageGallery'
import { getGames, saveGames } from './lib/stockStore'

export default function App() {
  const [games, setGames] = useState(getGames); const [editing, setEditing] = useState(null); const [query, setQuery] = useState('')
  useEffect(() => saveGames(games), [games])
  const shown = games.filter(g => `${g.nameZh} ${g.nameEn} ${g.sku}`.toLowerCase().includes(query.toLowerCase()))
  const save = game => { setGames(list => list.some(g => g.id === game.id) ? list.map(g => g.id === game.id ? game : g) : [game, ...list]); setEditing(null) }
  return <main className="mx-auto max-w-6xl p-4 sm:p-7"><header className="mb-7 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-teal-700 p-3 text-white"><Gamepad2 /></div><div><h1 className="text-xl font-bold">Meeple POS</h1><p className="text-sm text-slate-500">桌游库存维护</p></div></div><button onClick={() => setEditing({})} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 font-medium text-white shadow-sm"><Plus size={18}/>新增桌游</button></header>{editing !== null ? <section className="rounded-2xl bg-white p-5 shadow-sm sm:p-7"><h2 className="mb-6 text-lg font-bold">{editing.id ? '编辑桌游' : '新增桌游'}</h2><ItemForm initial={editing} onSave={save} onCancel={() => setEditing(null)} /></section> : <><div className="relative mb-5"><Search className="absolute left-3 top-2.5 text-slate-400" size={18}/><input className="pl-10" placeholder="搜索名称或 SKU" value={query} onChange={e => setQuery(e.target.value)}/></div><section className="grid gap-4 md:grid-cols-2">{shown.map(game => <article key={game.id} className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="p-4"><ImageGallery images={game.images}/></div><div className="space-y-3 border-t p-5"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{game.nameZh}</h2><p className="text-sm text-slate-500">{game.nameEn || '—'} · {game.category}</p></div><button onClick={() => setEditing(game)} className="h-9 rounded-lg border px-3 text-sm"><Pencil className="inline mr-1" size={15}/>编辑</button></div><div className="grid grid-cols-2 gap-2 text-sm text-slate-600"><span><Users className="mr-1 inline" size={15}/>{game.minPlayers}–{game.maxPlayers} 人</span><span>{game.duration} 分钟 · 重度 {game.weight}</span><span>库存 {game.totalSets} 套</span><span>位置 {game.location || '未设置'}</span></div><div className="flex items-center justify-between"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-medium text-teal-800">{game.status}</span><span className="text-xs text-slate-400">{game.sku || '无 SKU'}</span></div></div></article>)}</section>{!shown.length && <p className="py-16 text-center text-slate-500">未找到桌游</p>}</>}</main>
}
