import { useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight, CircleHelp, Crown, Eye, FileText, Moon, RotateCcw, Settings2, Skull, Sparkles, Sun, Swords, Users, X } from 'lucide-react'

const goodGodRoles = ['预言家','女巫','猎人','白痴','老流氓','守卫','骑士','长老','替死鬼','禁言长老','狐狸','驯熊师','守墓人','黑市商人','通灵师','爱神','摄梦人','乌鸦','魔术师','猎魔人']
const wolfRoleOptions = ['狼人','狼王','白狼王','狼美人','隐狼','雪狼','狼兄弟','梦魇','石像鬼','恶魔','恶灵骑士','血月使徒','机械狼']
const wolfRoles = new Set(wolfRoleOptions)
const godRoles = new Set(goodGodRoles)
const defaultRoles = [['预言家','神职'],['女巫','神职'],['猎人','神职'],['守卫','神职'],['狼人','狼人'],['狼人','狼人'],['狼人','狼人'],['狼人','狼人'],['平民','好人'],['平民','好人'],['平民','好人'],['平民','好人']]
const steps = [
  { title:'狼人行动', hint:'请狼人睁眼，选择今晚袭击的目标', icon:Moon }, { title:'守卫行动', hint:'请守卫睁眼，选择今晚守护的目标', icon:Sparkles },
  { title:'女巫行动', hint:'请女巫睁眼，决定是否使用药剂', icon:CircleHelp }, { title:'预言家查验', hint:'请预言家睁眼，选择要查验的玩家', icon:Eye },
  { title:'天亮了', hint:'公布昨夜结果，开始白天发言与放逐', icon:Sun }
]
const makePlayers=()=>defaultRoles.map(([role,camp],i)=>({id:i+1,role,camp,alive:true,selected:false,revealed:false}))
const roleColor=camp=>camp==='狼人'?'wolf':camp==='神职'?'god':'folk'

export default function App(){
 const [screen,setScreen]=useState('home'),[players,setPlayers]=useState(makePlayers),[step,setStep]=useState(0),[round,setRound]=useState(1),[logs,setLogs]=useState([]),[drawer,setDrawer]=useState(false),[message,setMessage]=useState('')
 const alive=players.filter(p=>p.alive).length,selected=players.find(p=>p.selected),current=steps[step]
 const summary=useMemo(()=>({wolves:players.filter(p=>p.camp==='狼人'&&p.alive).length,good:players.filter(p=>p.camp!=='狼人'&&p.alive).length}),[players])
 const choose=id=>setPlayers(ps=>ps.map(p=>({...p,selected:p.id===id&&p.alive})));
 const kill=id=>{const target=players.find(p=>p.id===id);if(!target?.alive)return;setPlayers(ps=>ps.map(p=>p.id===id?{...p,alive:false,selected:false}:p));setLogs(l=>[`第${round}${step===4?'天':'夜'}：${id}号玩家出局`,...l])}
 const next=()=>{if(selected&&step<4){setLogs(l=>[`第${round}夜 ${current.title}：选择 ${selected.id} 号玩家`,...l]);setPlayers(ps=>ps.map(p=>({...p,selected:false})))}if(step===4){setRound(r=>r+1);setStep(0)}else setStep(s=>s+1)}
 const newGame=()=>{setPlayers(makePlayers());setStep(0);setRound(1);setLogs([]);setScreen('game')}
 if(screen==='game')return <main className="app-shell game-shell"><header className="topbar"><button className="icon-btn" onClick={()=>setScreen('home')} aria-label="返回首页"><ChevronLeft/></button><Brand small/><div className="top-actions"><button className="pill" onClick={()=>setDrawer(true)}><Users size={16}/> 场上 {alive} 人</button><button className="icon-btn" onClick={()=>setDrawer(true)} aria-label="设置"><Settings2 size={18}/></button></div></header><div className="game-layout"><section className="stage"><div className="phase-line"><span>第 {round} 夜</span><i/><span>{current.title}</span><i/><span>共 {players.length} 人</span></div><div className="night-card"><div className="step-icon"><current.icon size={30}/></div><p className="eyebrow">NIGHT {round} · {String(step+1).padStart(2,'0')}</p><h1>{current.title}</h1><p>{current.hint}</p>{step===2&&<div className="choice-row"><button onClick={()=>setMessage('已记录：女巫使用解药')}>使用解药</button><button onClick={()=>setMessage('已记录：女巫使用毒药')}>使用毒药</button><button onClick={()=>setMessage('已记录：女巫今晚不开药')}>不开药</button></div>}{message&&<small className="toast">{message}</small>}</div><div className="player-grid">{players.map(p=><button key={p.id} onClick={()=>choose(p.id)} className={`player-card ${p.alive?'':'dead'} ${p.selected?'selected':''}`}><span className="number">{p.id}</span><span className="player-state">{p.alive?(p.selected?'已选择':'点击选择'):'已出局'}</span>{!p.alive&&<Skull size={17}/>}</button>)}</div><div className="flow-controls"><button className="ghost-btn" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ChevronLeft size={18}/> 上一步</button><button className="primary-btn" onClick={next}>{step===4?'进入下一夜':'确认，下一步'} <ChevronRight size={18}/></button></div></section><aside className="side-panel"><div className="panel-title"><span>场上情况</span><button onClick={()=>setDrawer(true)}>管理</button></div><div className="status-list">{players.map(p=><div key={p.id} className={!p.alive?'muted':''}><b>{p.id}号</b><span>{p.revealed?p.role:'身份未知'}</span><em className={p.alive?'alive':'out'}>{p.alive?'存活':'死亡'}</em></div>)}</div><button className="end-game" onClick={()=>setScreen('report')}>结束对局 <Swords size={15}/></button></aside></div>{drawer&&<PlayerDrawer {...{players,setPlayers,kill,onClose:()=>setDrawer(false)}}/>}</main>
 if(screen==='report')return <main className="app-shell report-page"><header className="topbar"><button className="icon-btn" onClick={()=>setScreen('game')}><ChevronLeft/></button><Brand small/><button className="pill" onClick={()=>setScreen('home')}>完成</button></header><section className="report-hero"><p>GAME REPORT</p><h1>第 {round} 局 · 夜色已明</h1><div className="result-stats"><div><b>{summary.wolves}</b><span>存活狼人</span></div><div><b>{summary.good}</b><span>存活好人</span></div><div><b>{logs.length}</b><span>关键记录</span></div></div></section><section className="report-grid"><div className="report-card"><h2><Crown size={18}/> 玩家身份</h2><div className="role-roster">{players.map(p=><div key={p.id} className={roleColor(p.camp)}><b>{p.id}号</b><span>{p.role}</span><em>{p.alive?'存活':'已出局'}</em></div>)}</div></div><div className="report-card"><h2><FileText size={18}/> 游戏记录</h2>{logs.length?<ol className="timeline">{logs.map((log,i)=><li key={i}>{log}</li>)}</ol>:<p className="empty-copy">本局尚未记录任何事件。</p>}<button className="primary-btn wide" onClick={newGame}><RotateCcw size={17}/> 再来一局</button></div></section></main>
 return <main className="app-shell home-page"><div className="home-aurora"/><header className="home-nav"><Brand/><button className="history-link" onClick={()=>setScreen('report')}><FileText size={17}/> 对局复盘</button></header><section className="home-main"><div className="intro"><div className="badge"><Sparkles size={15}/> 线下狼人杀 · 法官助手</div><h1>让每一夜的<br/><span>裁决，清晰有序。</span></h1><p>从身份配置、夜晚行动到白天放逐，<br/>一台设备掌控整局节奏。</p><div className="features"><span><Moon size={16}/> 夜晚流程引导</span><span><Eye size={16}/> 身份与状态管理</span><span><FileText size={16}/> 对局自动复盘</span></div></div><div className="setup-card"><div className="card-orbit orbit-a"/><div className="card-orbit orbit-b"/><p className="eyebrow">CREATE A NEW GAME</p><h2>今晚，谁在说谎？</h2><p className="setup-copy">默认预女猎守 · 四狼 · 四平民<br/>共 12 位玩家</p><div className="role-pills">{['预言家','女巫','猎人','守卫','狼人 ×4','平民 ×4'].map(x=><span key={x}>{x}</span>)}</div><button className="start-btn" onClick={newGame}>开始这局游戏 <ChevronRight size={19}/></button><button className="secondary-start" onClick={()=>setDrawer(true)}><Settings2 size={17}/> 调整身份配置</button></div></section><footer><span>⏾ 裁判专注于现场，而不是记忆流程</span><span>版本 1.0 · 离线可用</span></footer>{drawer&&<PlayerDrawer {...{players,setPlayers,kill,onClose:()=>setDrawer(false)}}/>}</main>
}
function Brand({small}) {return <div className={`brand ${small?'small':''}`}><span className="moon-mark">☾</span><b>{small?'月下裁决':'月下裁决'}</b><em>WEREWOLF JUDGE</em></div>}
function PlayerDrawer({players,setPlayers,kill,onClose}){const setRole=(id,role)=>setPlayers(list=>list.map(p=>p.id===id?{...p,role,camp:wolfRoles.has(role)?'狼人':godRoles.has(role)?'神职':'好人'}:p));return <div className="modal-backdrop"><section className="drawer"><div className="drawer-head"><div><p className="eyebrow">ROLE SETUP</p><h2>身份与玩家管理</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><p className="drawer-copy">使用下拉选单为每位玩家选择角色；游戏中可标记出局、公开身份。</p><div className="manage-list">{players.map(p=><div key={p.id}><b>{p.id}号</b><select aria-label={`${p.id}号角色`} className={`role-select ${roleColor(p.camp)}`} value={p.role} onChange={event=>setRole(p.id,event.target.value)}><optgroup label="村民"><option value="平民">平民</option></optgroup><optgroup label="好人神职">{goodGodRoles.map(role=><option key={role} value={role}>{role}</option>)}</optgroup><optgroup label="狼人阵营">{wolfRoleOptions.map(role=><option key={role} value={role}>{role}</option>)}</optgroup></select><button className="reveal" onClick={()=>setPlayers(list=>list.map(x=>x.id===p.id?{...x,revealed:!x.revealed}:x))}>{p.revealed?'隐藏':'公开'}</button><button className={p.alive?'kill':'revive'} onClick={()=>p.alive?kill(p.id):setPlayers(list=>list.map(x=>x.id===p.id?{...x,alive:true}:x))}>{p.alive?'出局':'复活'}</button></div>)}</div><button className="primary-btn wide" onClick={onClose}>保存设置</button></section></div>}
